_target_: shac.algorithms.shac.SHAC
_recursive_: False
actor_config:
  _target_: shac.models.actor.ActorStochasticMLP
  units: ${task.shac.actor_mlp.units}
  activation: elu
critic_config:
  _target_: shac.models.critic.CriticMLP
  units: ${task.shac.critic_mlp.units}
  activation: elu
actor_lr: 2e-3
critic_lr: 2e-3
lr_schedule: linear
target_critic_alpha: 0.2
obs_rms: True
ret_rms: False
critic_iterations: 16
critic_batches: 4
critic_method: td-lambda # ('td-lambda', 'one-step')
lam: 0.95
gamma: 0.99
max_epochs: 2000
steps_num: 32
grad_norm: 1.0
save_interval: 400
stochastic_eval: False
eval_runs: 12
train: ${general.train}
device: ${general.device}  
