defaults:
  - _self_
  - rewards:
    - action_penalty
    - object_pos_err
    - reach_bonus
    - rot_reward_delta
    - hand_joint_pos_err

name: repose_task

score_keys:
  - object_rot_diff
  - object_pos_err
  - reach_bonus
  - action_penalty
  - net_energy

env:
  _target_: warp.envs.ReposeTask
  num_envs: ${resolve_default:256,${num_envs}}
  episode_length: 250
  render: ${render}
  reward_params: 
    action_penalty: ${task.rewards.action_penalty}
    object_pos_err: ${task.rewards.object_pos_err}
    hand_joint_pos_err: ${task.rewards.hand_joint_pos_err}
    rot_reward_delta: ${task.rewards.rot_reward_delta}
    reach_bonus: ${task.rewards.reach_bonus}
  hand_type: ${hand:allegro}
  stochastic_init: true
  use_autograd: false
  use_graph_capture: false
  # use_graph_capture: ${eval:'("shac" not in "${alg.name}")'}
  no_grad: false


ppo:
  max_epochs: 1000
  save_best_after: 100
  save_frequency: 400
  num_actors: 2048
  minibatch_size: 16384
  steps_num: 32
  actor_mlp:
    units: [64, 64]
  score_to_win: 60000

player:
  deterministic: true
  games_num: 100000
  print_stats: true
